import nbformat as nbf
nb = nbf.v4.new_notebook()
nb.metadata['kernelspec'] = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}

nb.cells = [
    nbf.v4.new_markdown_cell(
        "# 05 Pure Quantum Models Training\n\n"
        "**No CNN backbone — pure quantum circuits on handcrafted features**\n\n"
        "Three quantum approaches compared:\n"
        "1. **Pure VQC** — AngleEmbedding + StronglyEntanglingLayers\n"
        "2. **Quantum Kernel SVM (QSVM)** — Quantum kernel matrix + classical SVC\n"
        "3. **Data Re-uploading QNN** — Input re-encoded at every layer\n\n"
        "All models operate on the 6-dimensional handcrafted features."
    ),

    # Cell 1: Imports, data loading, and label remapping
    nbf.v4.new_code_cell(
        "import sys, os, time\n"
        "sys.path.insert(0, os.path.abspath('../src'))\n"
        "\n"
        "import numpy as np\n"
        "import torch\n"
        "import torch.nn as nn\n"
        "import pennylane as qml\n"
        "from sklearn.svm import SVC\n"
        "from sklearn.preprocessing import StandardScaler, LabelEncoder\n"
        "from sklearn.metrics import accuracy_score, f1_score\n"
        "\n"
        "from utils.config import CFG\n"
        "from data.loader import load_dataset\n"
        "from data.preprocess import build_feature_matrix\n"
        "\n"
        "print('Loading dataset (200 images per class)...')\n"
        "train_rec, val_rec, test_rec = load_dataset(max_per_class=200)\n"
        "\n"
        "print('Extracting 6-dim handcrafted features...')\n"
        "X_train, y_train_raw = build_feature_matrix(train_rec, desc='Train')\n"
        "X_val, y_val_raw = build_feature_matrix(val_rec, desc='Val')\n"
        "X_test, y_test_raw = build_feature_matrix(test_rec, desc='Test')\n"
        "\n"
        "# Remap labels to contiguous 0..n_classes-1\n"
        "le = LabelEncoder()\n"
        "le.fit(np.concatenate([y_train_raw, y_val_raw, y_test_raw]))\n"
        "y_train = le.transform(y_train_raw)\n"
        "y_val = le.transform(y_val_raw)\n"
        "y_test = le.transform(y_test_raw)\n"
        "\n"
        "# Normalize features\n"
        "scaler = StandardScaler()\n"
        "X_train_s = scaler.fit_transform(X_train)\n"
        "X_val_s = scaler.transform(X_val)\n"
        "X_test_s = scaler.transform(X_test)\n"
        "\n"
        "n_features = X_train.shape[1]\n"
        "n_classes = len(le.classes_)\n"
        "print(f'Features: {n_features}, Classes: {n_classes}')\n"
        "print(f'Labels remapped to 0..{n_classes-1}')\n"
        "print(f'Shapes -> Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}')"
    ),

    # Cell 2: Pure VQC
    nbf.v4.new_code_cell(
        "# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "# MODEL 1: Pure VQC (AngleEmbedding + StronglyEntanglingLayers)\n"
        "# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "print('='*60)\n"
        "print('MODEL 1: Pure VQC')\n"
        "print('  AngleEmbedding + StronglyEntanglingLayers (6q, 6L)')\n"
        "print('='*60)\n"
        "\n"
        "n_q = n_features\n"
        "n_l = 6\n"
        "dev1 = qml.device('default.qubit', wires=n_q)\n"
        "\n"
        "@qml.qnode(dev1, interface='torch', diff_method='backprop')\n"
        "def pure_vqc_circuit(inputs, weights):\n"
        "    qml.AngleEmbedding(inputs, wires=range(n_q), rotation='Y')\n"
        "    qml.StronglyEntanglingLayers(weights, wires=range(n_q))\n"
        "    return [qml.expval(qml.PauliZ(w)) for w in range(n_q)]\n"
        "\n"
        "class PureVQC(nn.Module):\n"
        "    def __init__(self):\n"
        "        super().__init__()\n"
        "        self.qlayer = qml.qnn.TorchLayer(pure_vqc_circuit, {'weights': (n_l, n_q, 3)})\n"
        "        self.classifier = nn.Sequential(nn.Linear(n_q, 32), nn.ReLU(), nn.Linear(32, n_classes))\n"
        "    def forward(self, x):\n"
        "        return self.classifier(self.qlayer(x))\n"
        "\n"
        "pure_vqc = PureVQC()\n"
        "opt1 = torch.optim.Adam(pure_vqc.parameters(), lr=0.01)\n"
        "crit = nn.CrossEntropyLoss()\n"
        "X_tr = torch.tensor(X_train_s, dtype=torch.float32)\n"
        "y_tr = torch.tensor(y_train, dtype=torch.long)\n"
        "X_te = torch.tensor(X_test_s, dtype=torch.float32)\n"
        "\n"
        "t0 = time.time()\n"
        "for epoch in range(1, 31):\n"
        "    pure_vqc.train()\n"
        "    perm = torch.randperm(len(X_tr))\n"
        "    eloss = 0.0\n"
        "    for i in range(0, len(X_tr), 64):\n"
        "        idx = perm[i:i+64]\n"
        "        opt1.zero_grad()\n"
        "        loss = crit(pure_vqc(X_tr[idx]), y_tr[idx])\n"
        "        loss.backward()\n"
        "        opt1.step()\n"
        "        eloss += loss.item()\n"
        "    if epoch % 5 == 0 or epoch == 1:\n"
        "        print(f'  Epoch {epoch:>3}/30 | Loss: {eloss/(len(X_tr)//64):.4f} | {time.time()-t0:.0f}s')\n"
        "\n"
        "pure_vqc.eval()\n"
        "with torch.no_grad():\n"
        "    preds_vqc = torch.argmax(pure_vqc(X_te), dim=1).numpy()\n"
        "vqc_acc = accuracy_score(y_test, preds_vqc)\n"
        "vqc_f1 = f1_score(y_test, preds_vqc, average='macro', zero_division=0)\n"
        "print(f'\\nPure VQC -> Accuracy: {vqc_acc:.4f}, Macro F1: {vqc_f1:.4f} ({time.time()-t0:.0f}s)')"
    ),

    # Cell 3: Quantum Kernel SVM
    nbf.v4.new_code_cell(
        "# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "# MODEL 2: Quantum Kernel SVM (QSVM)\n"
        "# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "print('='*60)\n"
        "print('MODEL 2: Quantum Kernel SVM (QSVM)')\n"
        "print('  ZZ Feature Map kernel + classical SVC')\n"
        "print('='*60)\n"
        "\n"
        "dev2 = qml.device('default.qubit', wires=n_features)\n"
        "\n"
        "@qml.qnode(dev2, interface='numpy')\n"
        "def qkernel_circuit(x1, x2):\n"
        "    qml.AngleEmbedding(x1, wires=range(n_features), rotation='Y')\n"
        "    for i in range(n_features - 1):\n"
        "        qml.CNOT(wires=[i, i+1])\n"
        "        qml.RZ(x1[i] * x1[i+1], wires=i+1)\n"
        "        qml.CNOT(wires=[i, i+1])\n"
        "    qml.adjoint(qml.AngleEmbedding)(x2, wires=range(n_features), rotation='Y')\n"
        "    for i in range(n_features - 1):\n"
        "        qml.CNOT(wires=[i, i+1])\n"
        "        qml.RZ(-x2[i] * x2[i+1], wires=i+1)\n"
        "        qml.CNOT(wires=[i, i+1])\n"
        "    return qml.probs(wires=range(n_features))\n"
        "\n"
        "def qkernel(x1, x2):\n"
        "    return qkernel_circuit(x1, x2)[0]\n"
        "\n"
        "# Subsample for kernel computation\n"
        "np.random.seed(42)\n"
        "N_TR = min(300, len(X_train_s))\n"
        "N_TE = min(150, len(X_test_s))\n"
        "idx_tr = np.random.choice(len(X_train_s), N_TR, replace=False)\n"
        "idx_te = np.random.choice(len(X_test_s), N_TE, replace=False)\n"
        "Xk_tr, yk_tr = X_train_s[idx_tr], y_train[idx_tr]\n"
        "Xk_te, yk_te = X_test_s[idx_te], y_test[idx_te]\n"
        "\n"
        "print(f'Computing quantum kernel ({N_TR}x{N_TR} train, {N_TE}x{N_TR} test)...')\n"
        "t0 = time.time()\n"
        "K_train = np.zeros((N_TR, N_TR))\n"
        "for i in range(N_TR):\n"
        "    for j in range(i, N_TR):\n"
        "        k = qkernel(Xk_tr[i], Xk_tr[j])\n"
        "        K_train[i,j] = K_train[j,i] = k\n"
        "    if (i+1) % 50 == 0:\n"
        "        print(f'  Train kernel row {i+1}/{N_TR} ({time.time()-t0:.0f}s)')\n"
        "\n"
        "K_test = np.zeros((N_TE, N_TR))\n"
        "for i in range(N_TE):\n"
        "    for j in range(N_TR):\n"
        "        K_test[i,j] = qkernel(Xk_te[i], Xk_tr[j])\n"
        "print(f'Kernel computation: {time.time()-t0:.0f}s')\n"
        "\n"
        "qsvm = SVC(kernel='precomputed', C=1.0)\n"
        "qsvm.fit(K_train, yk_tr)\n"
        "preds_qsvm = qsvm.predict(K_test)\n"
        "qsvm_acc = accuracy_score(yk_te, preds_qsvm)\n"
        "qsvm_f1 = f1_score(yk_te, preds_qsvm, average='macro', zero_division=0)\n"
        "print(f'\\nQSVM -> Accuracy: {qsvm_acc:.4f}, Macro F1: {qsvm_f1:.4f}')"
    ),

    # Cell 4: Data Re-uploading QNN
    nbf.v4.new_code_cell(
        "# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "# MODEL 3: Data Re-uploading QNN\n"
        "# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "print('='*60)\n"
        "print('MODEL 3: Data Re-uploading QNN (8 layers)')\n"
        "print('='*60)\n"
        "\n"
        "n_l3 = 8\n"
        "dev3 = qml.device('default.qubit', wires=n_features)\n"
        "\n"
        "@qml.qnode(dev3, interface='torch', diff_method='backprop')\n"
        "def reupload_circuit(inputs, weights):\n"
        "    for layer in range(n_l3):\n"
        "        qml.AngleEmbedding(inputs, wires=range(n_features), rotation='Y')\n"
        "        for q in range(n_features):\n"
        "            qml.Rot(weights[layer,q,0], weights[layer,q,1], weights[layer,q,2], wires=q)\n"
        "        for q in range(n_features):\n"
        "            qml.CNOT(wires=[q, (q+1)%n_features])\n"
        "        if n_features >= 4:\n"
        "            for q in range(0, n_features-2, 2):\n"
        "                qml.CNOT(wires=[q, q+2])\n"
        "    return [qml.expval(qml.PauliZ(w)) for w in range(n_features)]\n"
        "\n"
        "class DataReupQNN(nn.Module):\n"
        "    def __init__(self):\n"
        "        super().__init__()\n"
        "        self.qlayer = qml.qnn.TorchLayer(reupload_circuit, {'weights': (n_l3, n_features, 3)})\n"
        "        self.classifier = nn.Sequential(nn.Linear(n_features, 64), nn.ReLU(), nn.Dropout(0.2), nn.Linear(64, n_classes))\n"
        "    def forward(self, x):\n"
        "        return self.classifier(self.qlayer(x))\n"
        "\n"
        "qnn = DataReupQNN()\n"
        "opt3 = torch.optim.Adam(qnn.parameters(), lr=0.005)\n"
        "sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt3, T_max=50)\n"
        "\n"
        "t0 = time.time()\n"
        "best_acc = 0\n"
        "for epoch in range(1, 51):\n"
        "    qnn.train()\n"
        "    perm = torch.randperm(len(X_tr))\n"
        "    eloss = 0.0\n"
        "    for i in range(0, len(X_tr), 64):\n"
        "        idx = perm[i:i+64]\n"
        "        opt3.zero_grad()\n"
        "        loss = crit(qnn(X_tr[idx]), y_tr[idx])\n"
        "        loss.backward()\n"
        "        opt3.step()\n"
        "        eloss += loss.item()\n"
        "    sched.step()\n"
        "    if epoch % 10 == 0 or epoch == 1:\n"
        "        qnn.eval()\n"
        "        with torch.no_grad():\n"
        "            vp = torch.argmax(qnn(torch.tensor(X_val_s, dtype=torch.float32)), dim=1).numpy()\n"
        "        va = accuracy_score(y_val, vp)\n"
        "        if va > best_acc:\n"
        "            best_acc = va\n"
        "            torch.save(qnn.state_dict(), '../outputs/models/qnn_best.pt')\n"
        "        print(f'  Epoch {epoch:>3}/50 | Loss: {eloss/(len(X_tr)//64):.4f} | Val: {va:.4f} | {time.time()-t0:.0f}s')\n"
        "\n"
        "qnn.load_state_dict(torch.load('../outputs/models/qnn_best.pt'))\n"
        "qnn.eval()\n"
        "with torch.no_grad():\n"
        "    preds_qnn = torch.argmax(qnn(X_te), dim=1).numpy()\n"
        "qnn_acc = accuracy_score(y_test, preds_qnn)\n"
        "qnn_f1 = f1_score(y_test, preds_qnn, average='macro', zero_division=0)\n"
        "print(f'\\nQNN -> Accuracy: {qnn_acc:.4f}, Macro F1: {qnn_f1:.4f} ({time.time()-t0:.0f}s)')"
    ),

    # Cell 5: Final comparison
    nbf.v4.new_code_cell(
        "print('\\n' + '='*70)\n"
        "print('  PURE QUANTUM MODELS — FINAL BENCHMARK')\n"
        "print('='*70)\n"
        "print(f'{\"Model\":<30} {\"Accuracy\":>12} {\"Macro F1\":>12}')\n"
        "print('-'*70)\n"
        "print(f'{\"Pure VQC\":<30} {vqc_acc:>12.4f} {vqc_f1:>12.4f}')\n"
        "print(f'{\"QSVM (Quantum Kernel)\":<30} {qsvm_acc:>12.4f} {qsvm_f1:>12.4f}')\n"
        "print(f'{\"Data Re-uploading QNN\":<30} {qnn_acc:>12.4f} {qnn_f1:>12.4f}')\n"
        "print('-'*70)\n"
        "print('Classical baselines (notebook 02, full dataset):')\n"
        "print(f'{\"  Random Forest\":<30} {0.5793:>12.4f} {0.4477:>12.4f}')\n"
        "print(f'{\"  SVM (Linear)\":<30} {0.2151:>12.4f} {0.0772:>12.4f}')\n"
        "print(f'{\"  Logistic Regression\":<30} {0.2458:>12.4f} {0.1221:>12.4f}')\n"
        "print('='*70)\n"
        "best_q = max([(vqc_acc,'Pure VQC'),(qsvm_acc,'QSVM'),(qnn_acc,'Data Re-uploading QNN')])\n"
        "print(f'\\n Best Pure Quantum Model: {best_q[1]} with {best_q[0]:.4f} accuracy')\n"
        "print('\\n Done!')"
    ),
]

nbf.write(nb, "notebooks/05_pure_quantum_models.ipynb")
print("Notebook 05 generated successfully.")
